# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hapdong' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'PageMenu'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'Kingfisher'
  # Pods for hapdong

end
